version: '3.8'

services:
  app:
    image: stockmeds/centurion-core:latest
    container_name: centurion-core
    restart: always
    depends_on:
      db:
        condition: service_healthy
    # env_file:
    #   - .env
    ports:
      - "8080:8080"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/check"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "10m"
#        max-file: "3"

  db:
    image: postgres:16-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: stockmeds
      POSTGRES_USER: centurion_core
      POSTGRES_PASSWORD: CenturionCore@800
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U centurion_core -d stockmeds"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
    driver_opts:
      type: "none"
      device: "/mnt/ebs-volume"
      o: "bind"
